---
title: "TAPR_grazing_v2"
output: html_document
date: "2025-05-07"

Author: Shelby Mead
Based on scripts developed by Gareth Rowell 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading packages, reading in data
```{r}
library(tidyverse)

read_in_grazing <- read_csv("data/tbl_MultiGrazing.csv")
read_in_grazing_landman <- read_csv("data/tbl_MultiGrazing_LandManUnit.csv")
read_in_LandManagement <- read_csv("data/tlu_LandManagementUnit.csv")
read_in_olddata <- read_csv("data/Grazing_calculations_final_RHCR_corr.csv")
```
Cleaning data to be able to add to old data
```{r}

multi_data <- read_in_grazing |>
  mutate(grazing_year = as.numeric(format(as.Date(LoadInDate, format = "%m/%d/%Y"), "%Y")))|> #date as date
  filter(AnimalTypeID != "Bi" & grazing_year >= 2024) |> #remove bison, sorting more recent years
  left_join(read_in_grazing_landman, by = "GrazingID") |> #join to tbl_MultiGrazing_LandManUnit
  left_join(read_in_LandManagement, by = "LandManUnitID") #join to tlu_LandManagementUnit to get pasture names

multi_data2 <- multi_data |> #renaming columns to match join table
   select(pasture = PastureName, acres = Acres, load_date_in = LoadInDate, load_date_out = LoadOutDate, goal_days_on = GoalDaysOn,actual_days_on = ActualDaysOn, head_on = HeadOn, head_off = HeadOff, lbs_on = LbsOn, lbs_off = LbsOff, grazing_year)

multi_data2$pasture <- gsub(" Pasture", "", multi_data2$pasture) #removing word "Pasture" from pasture column items

multi_data3 <- multi_data2 |>
  mutate(pasture = if_else(pasture == "East Traps", "East Traps and Two Section", if_else(pasture == "Two Section ", "East Traps and Two Section", pasture)))|>
  group_by(pasture, lbs_on) |>
  mutate(acres = sum(acres)) |>
  distinct()

# group_by(pasture) |>
# mutate(actual_days_on = sum(actual_days_on), head_on = sum(head_on), head_off = sum(head_off), lbs_on = sum(lbs_on), lbs_off = sum(lbs_off))|> select(!c(load_date_in, load_date_out))|>distinct()
```

Making calculations
```{r}


grazing_calc <- multi_data3 |>
  mutate(
    months = as.numeric( actual_days_on / 30),
	ave_no_head = ((head_on + head_off) / 2),
    ave_wt_on = lbs_on / head_on,
	ave_wt_off = lbs_off / head_off,
	ave_wt = (ave_wt_on + ave_wt_off) / 2,
	AUE1 = (ave_wt_off - ave_wt_on) / 2,
	AUE2 = (AUE1 + ave_wt_on) / 1000,
	AUM_per_head = AUE2 * months,
	Total_AUM = ave_no_head * AUM_per_head,
	Stocking_AUM_per_Acre = Total_AUM / acres,
	Total_AUY = Total_AUM / 12) |>
  group_by(pasture, grazing_year) |>
  mutate(Stocking_AUM_per_Acre = sum(Stocking_AUM_per_Acre))|>
  group_by(pasture, grazing_year) |>
  mutate(Total_AUY = sum(Total_AUY))|>
  mutate(Stocking_Acres_per_AUM = 1 / Stocking_AUM_per_Acre,
	Acres_per_AUY = acres / Total_AUY
  ) |>
  select(
    pasture, acres, grazing_year, actual_days_on, head_on, head_off, lbs_on, lbs_off, 
    months, ave_no_head,ave_wt_on, ave_wt_off, ave_wt,
	AUE1, AUE2, AUM_per_head, Total_AUM,
	Stocking_AUM_per_Acre, Stocking_Acres_per_AUM,
	Total_AUY, Acres_per_AUY
    )

combined_data <- bind_rows(read_in_olddata, grazing_calc)

export_table <- combined_data |>
  select(pasture, grazing_year, Stocking_AUM_per_Acre, Stocking_Acres_per_AUM, Total_AUY, Acres_per_AUY)|>
  distinct()|>
  arrange(pasture, grazing_year)

write.csv(export_table, file = "Tables/FinalGrazingCalculations.csv", row.names = FALSE)
```

Graphing
```{r}
# histograms

# months
ggplot(combined_data, aes(x = months)) +
  geom_histogram(binwidth = 0.5)
  
# ave_no_head
ggplot(combined_data, aes(x = ave_no_head)) +
  geom_histogram(binwidth = 50)
  

# ave_wt_on
ggplot(combined_data, aes(x = ave_wt_on)) +
  geom_histogram(binwidth = 50)
  

# ave_wt_off
ggplot(combined_data, aes(x = ave_wt_off)) +
  geom_histogram(binwidth = 50)

### Stocking Rate facet wrap plots ###########

ggplot(combined_data, aes(x = grazing_year, y = Stocking_Acres_per_AUM)) + 
  geom_point(size = 1) + 
  facet_wrap(~ pasture) + 
  labs(x = "Year", y = "Stocking Rate (Acres/AUM)") +
  theme(axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"), 
        strip.text = element_text(face = "bold", size = 11),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.margin = unit(c(1,1,1,1), 'cm'))

ggsave("FacetWrap_StockingRateAcre_AUM.jpg", path = "Graphs", dpi = 600, height = 5, width= 10)

ggplot(combined_data, aes(x = grazing_year, y = Stocking_AUM_per_Acre)) + 
  geom_point(size = 1) + 
  facet_wrap(~ pasture) + 
  labs(x = "Year", y = "Stocking Rate (AUM/Acre)") +
  theme(axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"), 
        strip.text = element_text(face = "bold", size = 11),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.margin = unit(c(1,1,1,1), 'cm'))

ggsave("FacetWrap_StockingRateAUM_Acre.jpg", path = "Graphs", dpi = 600, height = 5, width= 10)




ggplot(combined_data, aes(x = grazing_year, y = Stocking_AUM_per_Acre)) +
  geom_point() +
  geom_smooth(method = "lm")  + 
  labs(x = "Year", y = "Stocking Rate (AUM/acre)") +
  theme(axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"), 
        strip.text = element_text(face = "bold", size = 11),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.margin = unit(c(1,1,1,1), 'cm'))

ggsave("LinearReg_StockingRateAUM_Acre.jpg", path = "Graphs", dpi = 600, height = 5, width= 10)



ggplot(combined_data, aes(x = grazing_year, y = Stocking_Acres_per_AUM))+
  geom_point() +
  geom_smooth(method = "lm")  + 
  labs(x = "Year", y = "Stocking Rate (Acres/AUM)") +
   theme(axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"), 
        strip.text = element_text(face = "bold", size = 11),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.margin = unit(c(1,1,1,1), 'cm'))

ggsave("LinearReg_StockingRateAcre_AUM.jpg", path = "Graphs", dpi = 600, height = 5, width= 10)

#### Total AUY  facet wrap plot ############


ggplot(combined_data, aes(x = grazing_year, y = Total_AUY)) + 
  geom_point(size = 1) + 
  facet_wrap(~ pasture) + 
  labs(x = "Year", y = "Total AUY") +
  theme(axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"), 
        strip.text = element_text(face = "bold", size = 11),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.margin = unit(c(1,1,1,1), 'cm'))

ggsave("FacetWrap_Total_AUY.jpeg", path = "Graphs", dpi = 600, height = 5, width= 10)


#### Acres per AUY facet wrap plot #############


ggplot(combined_data, aes(x = grazing_year, y = Acres_per_AUY)) + 
  geom_point(size = 1) + 
  facet_wrap(~ pasture) + 
  labs(x = "Year", y = "Total AUY") +
    theme(axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"), 
        strip.text = element_text(face = "bold", size = 11),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.margin = unit(c(1,1,1,1), 'cm'))

ggsave("FacetWrap_Acres_AUY.jpeg", path = "Graphs", dpi = 600, height = 5, width= 10)



########## Stocking rate regression---------------------------------------------

head(combined_data)

attach(combined_data)


#fit simple linear regression model
model <- lm(Stocking_AUM_per_Acre ~ grazing_year)

#view model summary - R**2adj = 0.77

summary(model)

#define residuals
#res <- resid(model)

#produce residual vs. fitted plot
#plot(fitted(model), res)

#add a horizontal line at 0 
#abline(0,0)



# Plotting means and sds


grazing_msd <- combined_data %>%                       
  group_by(grazing_year)%>% 
  summarize(
    ave_stocking_rate_Acres = mean(Stocking_Acres_per_AUM),
    sd_Acres = sd(Stocking_Acres_per_AUM),
    ave_stocking_rate_AUM = mean(Stocking_AUM_per_Acre),
    sd_AUM = sd(Stocking_AUM_per_Acre)
  )

ggplot(grazing_msd, aes(x=grazing_year, y=ave_stocking_rate_Acres)) + 
  geom_errorbar(aes(ymin=ave_stocking_rate_Acres-sd_Acres, ymax=ave_stocking_rate_Acres+sd_Acres), width= 0) +
  geom_point(size=2) + 
  labs(x = "Year", y = "Stocking Rate (Acres/AUM)") +
  theme(axis.title.y = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"), 
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.margin = unit(c(1,1,1,1), 'cm'))


ggsave("MeansSDs_StockingRateAcres_AUM.jpg", path = "Graphs", dpi = 600, height = 5, width= 10)

ggplot(grazing_msd, aes(x=grazing_year, y=ave_stocking_rate_AUM)) + 
  geom_errorbar(aes(ymin=ave_stocking_rate_AUM-sd_AUM, ymax=ave_stocking_rate_AUM+sd_AUM), width= 0) +
  geom_point(size=2) + 
  labs(x = "Year", y = "Stocking Rate (AUM/Acres)") +
  theme(axis.title.y = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"), 
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.margin = unit(c(1,1,1,1), 'cm'))


ggsave("MeansSDs_StockingRateAUM_Acres.jpg", path = "Graphs",  dpi = 600, height = 5, width= 10)


# Coeefficient of Variation ----------------------------------------------------


grazing_CV <- grazing_msd  |>
  mutate(
    CV_stocking_rate = sd_Acres/ ave_stocking_rate_Acres
  )

ggplot(grazing_CV, aes(x = grazing_year, y = CV_stocking_rate)) +
  geom_point() +
  geom_smooth(method = "lm")
  labs(x = "Year", y = "Coefficient of Variation") +
  theme(axis.title.y = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"), 
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.margin = unit(c(1,1,1,1), 'cm'))

ggsave("VariationCoefficient_StockingRate.jpg", path = "Graphs",  dpi = 600, height = 5, width= 10)
#regression model - R**2adj = 0.42


#fit simple linear regression model
model <- lm( CV_stocking_rate ~ grazing_year)

#view model summary R^2 = 0.42

summary(model)


#  Hoof action!! ---------------------------------------------------------------

grazing_ha <- combined_data |>
  mutate(
    hoof_action = head_on * 4
  )

ggplot(grazing_ha, aes(x = grazing_year, y = hoof_action)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Year", y = "Hoof Action") +
  theme(axis.title.y = element_text(size = 14, face = "bold"),
        axis.title.x = element_text(size = 14, face = "bold"), 
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.margin = unit(c(1,1,1,1), 'cm'))

ggsave("HoofAction.jpg", path = "Graphs",  dpi = 600, height = 5, width= 10)

#fit simple linear regression model
model <- lm( hoof_action ~ grazing_year)

#view model summary R^2 = 0.42

summary(model)


```

